spring:
  config:
    activate:
      on-profile: jdbc

nexus:
  datasource:
    integration:
      url: jdbc:oracle:thin:@//${NEXUS_DB_INTEGRATION_HOST}:${NEXUS_DB_INTEGRATION_PORT}/${NEXUS_DB_INTEGRATION_SERVICE}
      driver-class-name: ${NEXUS_DB_DRIVER:oracle.jdbc.OracleDriver}
      username: ${NEXUS_DB_INTEGRATION_USER}
      password: ${NEXUS_DB_INTEGRATION_PASSWORD}
      hikari:
        maximum-pool-size: ${NEXUS_DB_POOL_MAX:5}
        minimum-idle: ${NEXUS_DB_POOL_MIN:1}
    regions:
      saitama:
        url: jdbc:oracle:thin:@//${NEXUS_DB_SAITAMA_HOST}:${NEXUS_DB_SAITAMA_PORT}/${NEXUS_DB_SAITAMA_SERVICE}
        driver-class-name: ${NEXUS_DB_DRIVER:oracle.jdbc.OracleDriver}
        username: ${NEXUS_DB_SAITAMA_USER}
        password: ${NEXUS_DB_SAITAMA_PASSWORD}
      fukushima:
        url: jdbc:oracle:thin:@//${NEXUS_DB_FUKUSHIMA_HOST}:${NEXUS_DB_FUKUSHIMA_PORT}/${NEXUS_DB_FUKUSHIMA_SERVICE}
        driver-class-name: ${NEXUS_DB_DRIVER:oracle.jdbc.OracleDriver}
        username: ${NEXUS_DB_FUKUSHIMA_USER}
        password: ${NEXUS_DB_FUKUSHIMA_PASSWORD}
      tochigi:
        url: jdbc:oracle:thin:@//${NEXUS_DB_TOCHIGI_HOST}:${NEXUS_DB_TOCHIGI_PORT}/${NEXUS_DB_TOCHIGI_SERVICE}
        driver-class-name: ${NEXUS_DB_DRIVER:oracle.jdbc.OracleDriver}
        username: ${NEXUS_DB_TOCHIGI_USER}
        password: ${NEXUS_DB_TOCHIGI_PASSWORD}
    region-configs:
      saitama:
        corporations:
          - musashino
          - saikan
          - fukushisousai
      fukushima:
        corporations:
          - fukushima
          - touhoku
          - gifu
      tochigi:
        corporations:
          - tochigi
          - shizuoka
          - tochigi_takusel